### PR TITLE
Add GPS Plugin

### PR DESCRIPTION
**Pull request by Sarath18**
Reference to issue #65 

Features set implemented:
- Display location marker on received message coordinate
- Center/follow mode (location marker always in the center)
- Set map type (Default / Satellite)
- Display location coordinates values

TODO:
- Add GPS Plugin icon (find/create an icon)
- Add a larger circle proportional to the covariance.

The qml modules required are `QtLocation` and `QtPositioning`. More details on Map item can be found [here](https://doc.qt.io/qt-5/qml-qtlocation-map.html#plugin-prop).

### CODE REVIEW

**Comment by Sarath18** [comment]
I have added visualization of position covariance through a larger circle. I have tested it out on 1-2 bag files and it looks fine but I am not 100% sure if the implementation is correct due to a lack of data. Can you please check it out?

For the location marker, I change the size of the circle according to the zoom level so that the current location is visible in all zoom levels. So now if the position covariance is small, you might have to zoom in to view the larger circle (similar to Google Maps on mobile).

I created a new icon for the GPS plugin using the point publisher icon from RViz and a map image. I tried to find a few royal free icons for GPS but didn't find anything interesting and also was not sure how to add copyright for the icon.

**Review by ahcorde — CHANGES_REQUESTED** [review]
can you add a note to the required qml modules (qml-module-qtpositioning qml-module-qtlocation) in the README ?

**Comment by ahcorde** [comment]
I have tried the GPS with a [simulation](https://github.com/osrf/drone_demo/). It looks pretty well

**Review by ahcorde — APPROVED** [review]

**Comment by chapulina** [comment]
> not sure how to add copyright for the icon.

The ideal case is to find an icon in the public domain, so we don't need to worry about copyright. For other licenses, it's a case-by-case basis. We can always just draw one ourselves. Ticketing an issue to see if a graphic designer feels motivated to contribute new icons could also be an option.

**Pull request merged**
